version: '3'
services:

  server:
    build: .
    container_name: tasks-app
    ports:
    - "8000:8000"
    command: sh -c "cd /CheckYourTasks
             && alembic upgrade head
             && python main.py"
    env_file:
      - .env
    depends_on:
      - database
    restart: always

  database:
    image: postgres
    container_name: tasks-db
    env_file:
      - .env